stages:
  - quality

variables:
  NODE_VERSION: '20'
  NPM_CONFIG_CACHE: '$CI_PROJECT_DIR/.npm'

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

.node_setup:
  image: node:${NODE_VERSION}
  before_script:
    - node --version
    - npm --version
    - npm ci --cache .npm --prefer-offline

prettier-check:
  extends: .node_setup
  stage: quality
  script:
    - npx prettier --check .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

eslint-check:
  extends: .node_setup
  stage: quality
  script:
    - npx eslint .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

type-check:
  extends: .node_setup
  stage: quality
  script:
    - npx tsc --noEmit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

tests:
  extends: .node_setup
  stage: quality
  script:
    - npm test -- --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 30 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
