name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/rsa-code/twd-mp1-ricardo-araujo.git
          git push gitlab HEAD:main --force
